[package]
name = "kondo"
version = "0.1.0"
authors = ["Trent Billington <trent.h.billington@gmail.com>"]
description = """
kondo is a filesystem cleaning tool that recursively searches directories
for known project structures and determines how much space you could save by
deleting the unnecessary files.
"""
documentation = "https://github.com/tbillington/kondo"
homepage = "https://github.com/tbillington/kondo"
repository = "https://github.com/tbillington/kondo"
readme = "README.md"
categories = ["command-line-utilities"]
license = "MIT"
exclude = ["test_dir"]
edition = "2018"

[dependencies]
walkdir = "2"
humansize = "1.1.0"

[profile.release]
incremental = false
lto = true
codegen-units = 1